import React from "react";

export default function ProductDetailsPage() {
  return (
    <>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
      <div>ProductDetailsPage</div>
    </>
  );
}
